FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the binary
RUN CGO_ENABLED=0 go build -o user-service cmd/user/main.go

# Final Stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/user-service .

# Expose gRPC port
EXPOSE 9090

CMD ["./user-service"]
