// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"coca-ai/internal/handler"
	"coca-ai/internal/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApp() *gin.Engine {
	pingHandler := handler.NewPingHandler()
	engine := ioc.InitWebServer(pingHandler)
	return engine
}
