// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"coca-ai/internal/handler"
	"coca-ai/internal/handler/middleware"
	"coca-ai/internal/ioc"
	"coca-ai/internal/mq"
	"coca-ai/internal/repository"
	"coca-ai/internal/repository/dao"
	"coca-ai/internal/service"
	"coca-ai/pkg/jwtx"
)

// Injectors from wire.go:

func InitApp() *App {
	pingHandler := handler.NewPingHandler()
	userService := ioc.InitUserGRPCClient()
	jwtHandler := jwtx.NewJWTHandler()
	userHandler := handler.NewUserHandler(userService, jwtHandler)
	db := ioc.InitDB()
	sessionDAO := dao.NewSessionDAO(db)
	sessionRepository := repository.NewSessionRepository(sessionDAO)
	messageDAO := dao.NewMessageDAO(db)
	cmdable := ioc.InitRedis()
	messageCache := ioc.InitMessageCache(cmdable)
	messageRepository := repository.NewMessageRepository(messageDAO, messageCache)
	chatClient := ioc.InitLLMClient()
	producer := ioc.InitKafkaProducer()
	contextService := service.NewContextService(messageRepository, chatClient)
	chatService := service.NewChatService(sessionRepository, messageRepository, chatClient, producer, contextService)
	chatHandler := handler.NewChatHandler(chatService)
	loginJWTMiddleware := middleware.NewLoginJWTMiddleware(jwtHandler, cmdable)
	engine := ioc.InitWebServer(pingHandler, userHandler, chatHandler, loginJWTMiddleware)
	baseConsumer := ioc.InitKafkaConsumer()
	messagePersistHandler := mq.NewMessagePersistHandler(messageDAO)
	consumer := ioc.BindKafkaHandlers(baseConsumer, messagePersistHandler)
	app := NewApp(engine, consumer)
	return app
}
